# TCL File Generated by Component Editor 24.1
# Thu Jun 25 11:04:30 ICT 2026
# DO NOT MODIFY


# 
# top "top" v1.0
#  2026.06.25.11:04:30
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module top
# 
set_module_property DESCRIPTION ""
set_module_property NAME top
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME top
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file conv.vhd VHDL PATH conv.vhd
add_fileset_file packet_manager.vhd VHDL PATH packet_manager.vhd
add_fileset_file top.vhd VHDL PATH top.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter IMG_WIDTH INTEGER 640
set_parameter_property IMG_WIDTH DEFAULT_VALUE 640
set_parameter_property IMG_WIDTH DISPLAY_NAME IMG_WIDTH
set_parameter_property IMG_WIDTH TYPE INTEGER
set_parameter_property IMG_WIDTH UNITS None
set_parameter_property IMG_WIDTH HDL_PARAMETER true
add_parameter DATA_WIDTH INTEGER 8
set_parameter_property DATA_WIDTH DEFAULT_VALUE 8
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clock
set_interface_property slave associatedReset reset_sink
set_interface_property slave bitsPerSymbol 8
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 0
set_interface_property slave maximumPendingWriteTransactions 0
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave avs_address address Input 1
add_interface_port slave avs_read read Input 1
add_interface_port slave avs_readdata readdata Output 32
add_interface_port slave avs_write write Input 1
add_interface_port slave avs_writedata writedata Input 32
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point ram_in
# 
add_interface ram_in avalon start
set_interface_property ram_in addressUnits SYMBOLS
set_interface_property ram_in associatedClock clock
set_interface_property ram_in associatedReset reset_sink
set_interface_property ram_in bitsPerSymbol 8
set_interface_property ram_in burstOnBurstBoundariesOnly false
set_interface_property ram_in burstcountUnits WORDS
set_interface_property ram_in doStreamReads false
set_interface_property ram_in doStreamWrites false
set_interface_property ram_in holdTime 0
set_interface_property ram_in linewrapBursts false
set_interface_property ram_in maximumPendingReadTransactions 0
set_interface_property ram_in maximumPendingWriteTransactions 0
set_interface_property ram_in readLatency 0
set_interface_property ram_in readWaitTime 1
set_interface_property ram_in setupTime 0
set_interface_property ram_in timingUnits Cycles
set_interface_property ram_in writeWaitTime 0
set_interface_property ram_in ENABLED true
set_interface_property ram_in EXPORT_OF ""
set_interface_property ram_in PORT_NAME_MAP ""
set_interface_property ram_in CMSIS_SVD_VARIABLES ""
set_interface_property ram_in SVD_ADDRESS_GROUP ""

add_interface_port ram_in ram_in_address address Output 32
add_interface_port ram_in ram_in_read read Output 1
add_interface_port ram_in ram_in_readdata readdata Input "((data_width-1)) - (0) + 1"
add_interface_port ram_in ram_in_waitrequest waitrequest Input 1


# 
# connection point ram_out
# 
add_interface ram_out avalon start
set_interface_property ram_out addressUnits SYMBOLS
set_interface_property ram_out associatedClock clock
set_interface_property ram_out associatedReset reset_sink
set_interface_property ram_out bitsPerSymbol 8
set_interface_property ram_out burstOnBurstBoundariesOnly false
set_interface_property ram_out burstcountUnits WORDS
set_interface_property ram_out doStreamReads false
set_interface_property ram_out doStreamWrites false
set_interface_property ram_out holdTime 0
set_interface_property ram_out linewrapBursts false
set_interface_property ram_out maximumPendingReadTransactions 0
set_interface_property ram_out maximumPendingWriteTransactions 0
set_interface_property ram_out readLatency 0
set_interface_property ram_out readWaitTime 1
set_interface_property ram_out setupTime 0
set_interface_property ram_out timingUnits Cycles
set_interface_property ram_out writeWaitTime 0
set_interface_property ram_out ENABLED true
set_interface_property ram_out EXPORT_OF ""
set_interface_property ram_out PORT_NAME_MAP ""
set_interface_property ram_out CMSIS_SVD_VARIABLES ""
set_interface_property ram_out SVD_ADDRESS_GROUP ""

add_interface_port ram_out ram_out_address address Output 32
add_interface_port ram_out ram_out_waitrequest waitrequest Input 1
add_interface_port ram_out ram_out_write write Output 1
add_interface_port ram_out ram_out_writedata writedata Output "((data_width-1)) - (0) + 1"

