// sys_mm_interconnect_3.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 24.1 1077

`timescale 1 ps / 1 ps
module sys_mm_interconnect_3 (
		input  wire        clk_0_clk_clk,                                          //                                        clk_0_clk.clk
		input  wire        new_component_0_reset_sink_reset_bridge_in_reset_reset, // new_component_0_reset_sink_reset_bridge_in_reset.reset
		input  wire [19:0] new_component_0_ram_out_address,                        //                          new_component_0_ram_out.address
		output wire        new_component_0_ram_out_waitrequest,                    //                                                 .waitrequest
		input  wire        new_component_0_ram_out_write,                          //                                                 .write
		input  wire [7:0]  new_component_0_ram_out_writedata,                      //                                                 .writedata
		output wire [11:0] ram_out_s1_address,                                     //                                       ram_out_s1.address
		output wire        ram_out_s1_write,                                       //                                                 .write
		input  wire [7:0]  ram_out_s1_readdata,                                    //                                                 .readdata
		output wire [7:0]  ram_out_s1_writedata,                                   //                                                 .writedata
		output wire        ram_out_s1_chipselect,                                  //                                                 .chipselect
		output wire        ram_out_s1_clken                                        //                                                 .clken
	);

	wire         new_component_0_ram_out_translator_avalon_universal_master_0_waitrequest;   // ram_out_s1_translator:uav_waitrequest -> new_component_0_ram_out_translator:uav_waitrequest
	wire   [7:0] new_component_0_ram_out_translator_avalon_universal_master_0_readdata;      // ram_out_s1_translator:uav_readdata -> new_component_0_ram_out_translator:uav_readdata
	wire         new_component_0_ram_out_translator_avalon_universal_master_0_debugaccess;   // new_component_0_ram_out_translator:uav_debugaccess -> ram_out_s1_translator:uav_debugaccess
	wire  [19:0] new_component_0_ram_out_translator_avalon_universal_master_0_address;       // new_component_0_ram_out_translator:uav_address -> ram_out_s1_translator:uav_address
	wire         new_component_0_ram_out_translator_avalon_universal_master_0_read;          // new_component_0_ram_out_translator:uav_read -> ram_out_s1_translator:uav_read
	wire   [0:0] new_component_0_ram_out_translator_avalon_universal_master_0_byteenable;    // new_component_0_ram_out_translator:uav_byteenable -> ram_out_s1_translator:uav_byteenable
	wire         new_component_0_ram_out_translator_avalon_universal_master_0_readdatavalid; // ram_out_s1_translator:uav_readdatavalid -> new_component_0_ram_out_translator:uav_readdatavalid
	wire         new_component_0_ram_out_translator_avalon_universal_master_0_lock;          // new_component_0_ram_out_translator:uav_lock -> ram_out_s1_translator:uav_lock
	wire         new_component_0_ram_out_translator_avalon_universal_master_0_write;         // new_component_0_ram_out_translator:uav_write -> ram_out_s1_translator:uav_write
	wire   [7:0] new_component_0_ram_out_translator_avalon_universal_master_0_writedata;     // new_component_0_ram_out_translator:uav_writedata -> ram_out_s1_translator:uav_writedata
	wire   [0:0] new_component_0_ram_out_translator_avalon_universal_master_0_burstcount;    // new_component_0_ram_out_translator:uav_burstcount -> ram_out_s1_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (20),
		.AV_DATA_W                   (8),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (1),
		.UAV_ADDRESS_W               (20),
		.UAV_BURSTCOUNT_W            (1),
		.USE_READ                    (0),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (0),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (1),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) new_component_0_ram_out_translator (
		.clk                    (clk_0_clk_clk),                                                              //                       clk.clk
		.reset                  (new_component_0_reset_sink_reset_bridge_in_reset_reset),                     //                     reset.reset
		.uav_address            (new_component_0_ram_out_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (new_component_0_ram_out_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (new_component_0_ram_out_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (new_component_0_ram_out_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (new_component_0_ram_out_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (new_component_0_ram_out_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (new_component_0_ram_out_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (new_component_0_ram_out_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (new_component_0_ram_out_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (new_component_0_ram_out_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (new_component_0_ram_out_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (new_component_0_ram_out_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (new_component_0_ram_out_waitrequest),                                        //                          .waitrequest
		.av_write               (new_component_0_ram_out_write),                                              //                          .write
		.av_writedata           (new_component_0_ram_out_writedata),                                          //                          .writedata
		.av_burstcount          (1'b1),                                                                       //               (terminated)
		.av_byteenable          (1'b1),                                                                       //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                       //               (terminated)
		.av_begintransfer       (1'b0),                                                                       //               (terminated)
		.av_chipselect          (1'b0),                                                                       //               (terminated)
		.av_read                (1'b0),                                                                       //               (terminated)
		.av_readdata            (),                                                                           //               (terminated)
		.av_readdatavalid       (),                                                                           //               (terminated)
		.av_lock                (1'b0),                                                                       //               (terminated)
		.av_debugaccess         (1'b0),                                                                       //               (terminated)
		.uav_clken              (),                                                                           //               (terminated)
		.av_clken               (1'b1),                                                                       //               (terminated)
		.uav_response           (2'b00),                                                                      //               (terminated)
		.av_response            (),                                                                           //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                       //               (terminated)
		.av_writeresponsevalid  ()                                                                            //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (12),
		.AV_DATA_W                      (8),
		.UAV_DATA_W                     (8),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (1),
		.UAV_BYTEENABLE_W               (1),
		.UAV_ADDRESS_W                  (20),
		.UAV_BURSTCOUNT_W               (1),
		.AV_READLATENCY                 (1),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (1),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) ram_out_s1_translator (
		.clk                    (clk_0_clk_clk),                                                              //                      clk.clk
		.reset                  (new_component_0_reset_sink_reset_bridge_in_reset_reset),                     //                    reset.reset
		.uav_address            (new_component_0_ram_out_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (new_component_0_ram_out_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (new_component_0_ram_out_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (new_component_0_ram_out_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (new_component_0_ram_out_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (new_component_0_ram_out_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (new_component_0_ram_out_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (new_component_0_ram_out_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (new_component_0_ram_out_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (new_component_0_ram_out_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (new_component_0_ram_out_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (ram_out_s1_address),                                                         //      avalon_anti_slave_0.address
		.av_write               (ram_out_s1_write),                                                           //                         .write
		.av_readdata            (ram_out_s1_readdata),                                                        //                         .readdata
		.av_writedata           (ram_out_s1_writedata),                                                       //                         .writedata
		.av_chipselect          (ram_out_s1_chipselect),                                                      //                         .chipselect
		.av_clken               (ram_out_s1_clken),                                                           //                         .clken
		.av_read                (),                                                                           //              (terminated)
		.av_begintransfer       (),                                                                           //              (terminated)
		.av_beginbursttransfer  (),                                                                           //              (terminated)
		.av_burstcount          (),                                                                           //              (terminated)
		.av_byteenable          (),                                                                           //              (terminated)
		.av_readdatavalid       (1'b0),                                                                       //              (terminated)
		.av_waitrequest         (1'b0),                                                                       //              (terminated)
		.av_writebyteenable     (),                                                                           //              (terminated)
		.av_lock                (),                                                                           //              (terminated)
		.uav_clken              (1'b0),                                                                       //              (terminated)
		.av_debugaccess         (),                                                                           //              (terminated)
		.av_outputenable        (),                                                                           //              (terminated)
		.uav_response           (),                                                                           //              (terminated)
		.av_response            (2'b00),                                                                      //              (terminated)
		.uav_writeresponsevalid (),                                                                           //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                        //              (terminated)
	);

endmodule
