-- =============================================================================
-- File    : sys_top.vhd
-- Mô tả   : Top-level wrapper cho toàn bộ hệ thống.
--            Instantiate sys (Qsys — chứa HPS + top_0 + f2h_sdram).
--            Tất cả kết nối HPS↔FPGA đã được đi dây nội bộ trong Qsys,
--            sys_top chỉ expose các chân vật lý ra board.
-- Board   : DE10-Nano / DE1-SoC (Cyclone V)
-- =============================================================================

library IEEE;
use IEEE.std_logic_1164.all;

entity sys_top is
    port (
        -- ---------------------------------------------------------------------
        -- Clock & Reset
        -- ---------------------------------------------------------------------
        FPGA_CLK1_50        : in    std_logic;
        KEY                 : in    std_logic_vector(1 downto 0);  -- KEY[0] = reset_n

        -- ---------------------------------------------------------------------
        -- HPS DDR3 SDRAM
        -- ---------------------------------------------------------------------
        HPS_DDR3_ADDR       : out   std_logic_vector(12 downto 0);
        HPS_DDR3_BA         : out   std_logic_vector(2 downto 0);
        HPS_DDR3_CK_P       : out   std_logic;
        HPS_DDR3_CK_N       : out   std_logic;
        HPS_DDR3_CKE        : out   std_logic;
        HPS_DDR3_CS_N       : out   std_logic;
        HPS_DDR3_RAS_N      : out   std_logic;
        HPS_DDR3_CAS_N      : out   std_logic;
        HPS_DDR3_WE_N       : out   std_logic;
        HPS_DDR3_RESET_N    : out   std_logic;
        HPS_DDR3_DQ         : inout std_logic_vector(7 downto 0);
        HPS_DDR3_DQS_P      : inout std_logic;
        HPS_DDR3_DQS_N      : inout std_logic;
        HPS_DDR3_ODT        : out   std_logic;
        HPS_DDR3_DM         : out   std_logic;
        HPS_DDR3_RZQ        : in    std_logic;

        -- ---------------------------------------------------------------------
        -- HPS Ethernet EMAC0
        -- ---------------------------------------------------------------------
        HPS_ENET_TX_CLK     : out   std_logic;
        HPS_ENET_TXD0       : out   std_logic;
        HPS_ENET_TXD1       : out   std_logic;
        HPS_ENET_TXD2       : out   std_logic;
        HPS_ENET_TXD3       : out   std_logic;
        HPS_ENET_RXD0       : in    std_logic;
        HPS_ENET_MDIO       : inout std_logic;
        HPS_ENET_MDC        : out   std_logic;
        HPS_ENET_RX_CTL     : in    std_logic;
        HPS_ENET_TX_CTL     : out   std_logic;
        HPS_ENET_RX_CLK     : in    std_logic;
        HPS_ENET_RXD1       : in    std_logic;
        HPS_ENET_RXD2       : in    std_logic;
        HPS_ENET_RXD3       : in    std_logic
    );
end entity sys_top;

architecture rtl of sys_top is

    -- =========================================================================
    -- Component sys  (generated by Qsys / Platform Designer)
    -- Port list lấy nguyên từ sys_inst.vhd
    -- =========================================================================
    component sys is
        port (
            clk_clk                          : in    std_logic;
            reset_reset_n                    : in    std_logic;
            -- DDR3
            memory_mem_a                     : out   std_logic_vector(12 downto 0);
            memory_mem_ba                    : out   std_logic_vector(2 downto 0);
            memory_mem_ck                    : out   std_logic;
            memory_mem_ck_n                  : out   std_logic;
            memory_mem_cke                   : out   std_logic;
            memory_mem_cs_n                  : out   std_logic;
            memory_mem_ras_n                 : out   std_logic;
            memory_mem_cas_n                 : out   std_logic;
            memory_mem_we_n                  : out   std_logic;
            memory_mem_reset_n               : out   std_logic;
            memory_mem_dq                    : inout std_logic_vector(7 downto 0);
            memory_mem_dqs                   : inout std_logic;
            memory_mem_dqs_n                 : inout std_logic;
            memory_mem_odt                   : out   std_logic;
            memory_mem_dm                    : out   std_logic;
            memory_oct_rzqin                 : in    std_logic;
            -- EMAC0
            hps_io_hps_io_emac0_inst_TX_CLK  : out   std_logic;
            hps_io_hps_io_emac0_inst_TXD0    : out   std_logic;
            hps_io_hps_io_emac0_inst_TXD1    : out   std_logic;
            hps_io_hps_io_emac0_inst_TXD2    : out   std_logic;
            hps_io_hps_io_emac0_inst_TXD3    : out   std_logic;
            hps_io_hps_io_emac0_inst_RXD0    : in    std_logic;
            hps_io_hps_io_emac0_inst_MDIO    : inout std_logic;
            hps_io_hps_io_emac0_inst_MDC     : out   std_logic;
            hps_io_hps_io_emac0_inst_RX_CTL  : in    std_logic;
            hps_io_hps_io_emac0_inst_TX_CTL  : out   std_logic;
            hps_io_hps_io_emac0_inst_RX_CLK  : in    std_logic;
            hps_io_hps_io_emac0_inst_RXD1    : in    std_logic;
            hps_io_hps_io_emac0_inst_RXD2    : in    std_logic;
            hps_io_hps_io_emac0_inst_RXD3    : in    std_logic;
            -- MPU events
            hps_0_h2f_mpu_events_eventi      : in    std_logic;
            hps_0_h2f_mpu_events_evento      : out   std_logic;
            hps_0_h2f_mpu_events_standbywfe  : out   std_logic_vector(1 downto 0);
            hps_0_h2f_mpu_events_standbywfi  : out   std_logic_vector(1 downto 0)
        );
    end component sys;

    -- MPU event sinks (không dùng, chỉ để tránh unconnected warning)
    signal mpu_evento_s    : std_logic;
    signal mpu_standby_wfe : std_logic_vector(1 downto 0);
    signal mpu_standby_wfi : std_logic_vector(1 downto 0);

begin

    -- =========================================================================
    -- u_sys : toàn bộ hệ thống Qsys
    --   - HPS, DDR3, EMAC0 nối ra chân board bên dưới
    --   - top_0 (packet_manager + conv) kết nối nội bộ với:
    --       h2f_lw_axi_master  → top_0.slave  (HPS điều khiển)
    --       top_0.ram_in       → f2h_sdram0_data (đọc ảnh DDR3)
    --       top_0.ram_out      → f2h_sdram0_data (ghi kết quả DDR3)
    --   Không có port nào của top_0 cần expose ra sys_top
    -- =========================================================================
    u_sys : component sys
        port map (
            clk_clk                          => FPGA_CLK1_50,
            reset_reset_n                    => KEY(0),

            -- DDR3
            memory_mem_a                     => HPS_DDR3_ADDR,
            memory_mem_ba                    => HPS_DDR3_BA,
            memory_mem_ck                    => HPS_DDR3_CK_P,
            memory_mem_ck_n                  => HPS_DDR3_CK_N,
            memory_mem_cke                   => HPS_DDR3_CKE,
            memory_mem_cs_n                  => HPS_DDR3_CS_N,
            memory_mem_ras_n                 => HPS_DDR3_RAS_N,
            memory_mem_cas_n                 => HPS_DDR3_CAS_N,
            memory_mem_we_n                  => HPS_DDR3_WE_N,
            memory_mem_reset_n               => HPS_DDR3_RESET_N,
            memory_mem_dq                    => HPS_DDR3_DQ,
            memory_mem_dqs                   => HPS_DDR3_DQS_P,
            memory_mem_dqs_n                 => HPS_DDR3_DQS_N,
            memory_mem_odt                   => HPS_DDR3_ODT,
            memory_mem_dm                    => HPS_DDR3_DM,
            memory_oct_rzqin                 => HPS_DDR3_RZQ,

            -- EMAC0
            hps_io_hps_io_emac0_inst_TX_CLK  => HPS_ENET_TX_CLK,
            hps_io_hps_io_emac0_inst_TXD0    => HPS_ENET_TXD0,
            hps_io_hps_io_emac0_inst_TXD1    => HPS_ENET_TXD1,
            hps_io_hps_io_emac0_inst_TXD2    => HPS_ENET_TXD2,
            hps_io_hps_io_emac0_inst_TXD3    => HPS_ENET_TXD3,
            hps_io_hps_io_emac0_inst_RXD0    => HPS_ENET_RXD0,
            hps_io_hps_io_emac0_inst_MDIO    => HPS_ENET_MDIO,
            hps_io_hps_io_emac0_inst_MDC     => HPS_ENET_MDC,
            hps_io_hps_io_emac0_inst_RX_CTL  => HPS_ENET_RX_CTL,
            hps_io_hps_io_emac0_inst_TX_CTL  => HPS_ENET_TX_CTL,
            hps_io_hps_io_emac0_inst_RX_CLK  => HPS_ENET_RX_CLK,
            hps_io_hps_io_emac0_inst_RXD1    => HPS_ENET_RXD1,
            hps_io_hps_io_emac0_inst_RXD2    => HPS_ENET_RXD2,
            hps_io_hps_io_emac0_inst_RXD3    => HPS_ENET_RXD3,

            -- MPU events (không dùng)
            hps_0_h2f_mpu_events_eventi      => '0',
            hps_0_h2f_mpu_events_evento      => mpu_evento_s,
            hps_0_h2f_mpu_events_standbywfe  => mpu_standby_wfe,
            hps_0_h2f_mpu_events_standbywfi  => mpu_standby_wfi
        );

end architecture rtl;